//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int cartId { get; set; }
        public int productId { get; set; }
        public int userId { get; set; }
        public int cardStatus { get; set; }
    
        public virtual User User { get; set; }
        public virtual Item Item { get; set; }
    }
}
